[accessibility]
ui_scale = 1.1500000096857548

[audio]
enable_overdrive = true

[backdrop]
enabled = true

[bar]
order = [ "default" ]

    [bar.default]
    background_opacity = 0.64999998547136784
    border = "primary"
    capsule_thickness = 0.74999998696148396
    center = [ "audio_visualizer", "clock", "audio_visualizer" ]
    end = [ "tray", "group:g1", "group:g2", "session" ]
    font_family = "Monocraft"
    margin_ends = 0
    position = "left"
    radius = 0
    radius_bottom_left = 0
    radius_top_left = 0
    scale = 1.1500000096857548
    start = [ "launcher", "workspaces", "cat" ]
    thickness = 48
    widget_spacing = 10

        [bar.default.monitor.DP-1]
        center = [ "audio_visualizer", "clock", "audio_visualizer" ]
        end = [ "tray", "group:g1", "recorder", "group:g2", "session" ]
        position = "right"

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface_variant"
        id = "g1"
        members = [ "widget_2", "todo" ]
        opacity = 0.75
        padding = 6.0
        radius = 6.0

        [[bar.default.capsule_group]]
        accordion = false
        accordion_direction = "end"
        border = "primary"
        enabled = true
        fill = "surface_variant"
        id = "g2"
        members = [ "network", "bluetooth", "volume", "battery" ]
        opacity = 0.75
        padding = 6.0
        radius = 6.0

[control_center]
hidden_tabs = [ "media", "monitor", "power", "network", "weather" ]
sidebar = "none"
sidebar_section = "none"
width = 900

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "nightlight"

[desktop_widgets]
schema_version = 2
widget_order = [ "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 528.0
    box_width = 2528.0
    cx = 1264.0
    cy = 1176.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = -0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        bands = 68
        centered = false
        color_1 = "#510BEF"
        color_2 = "on_surface_variant"
        reversed = false
        show_when_idle = true

[idle]
behavior_order = [ "screen-off", "lock", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 1200.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 1800.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 900.0

[lockscreen]
blur_intensity = 0.24999999441206455
tint_intensity = 0.14999999664723873
wallpaper = "/home/niximkopf/.nixos/assets/wallpaper/wallhaven-5ypg33.jpg"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@winit", "lockscreen-login-box@DP-1", "lockscreen-login-box@DP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 1280.0
    cy = 1258.0
    output = "DP-1"
    placement_height = 1440.0
    placement_width = 2560.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-2"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "DP-2"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@winit"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 618.0
    output = "winit"
    placement_height = 0.0
    placement_width = 0.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@winit".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[notification]
background_opacity = 0.64999998547136784
history_retention_hours = 10
max_visible = 5

[osd]
background_opacity = 0.64999998547136784
position = "top_right"
position_vertical = "top_right"

[plugin_settings."nightwatch75/todo"]
panel_open_near_click = false
panel_placement = "floating"
panel_position = "center"

[plugin_settings."thepunkoff/pomodoro"]
long-break-duration = 20
sessions-before-long-break = 2
short-break-duration = 10
work-duration = 30

[plugins]
enabled = [
    "noctalia/kaomoji",
    "nightwatch75/todo",
    "noctalia/timer",
    "weinguyen/opencode-companion",
    "thepunkoff/pomodoro",
    "radimous/prismlauncher-instances",
    "cleboost/ssh-launcher",
    "rylos/syncthing",
    "noctalia/bongocat",
    "dotnetrob/cat"
]

[shell]
app_icon_color = "primary"
app_icon_colorize = true
avatar_path = "/home/niximkopf/Pictures/PFP/emilia thuglife.jpeg"
clipboard_history_max_entries = 50
font_family = "Monocraft"
screen_time_enabled = true

    [shell.launcher]
    categories = false
    compact = true
    pinned = [
        "librewolf",
        "discord",
        "steam",
        "nemo",
        "LocalSend",
        "code",
        "anki",
        "saber",
        "startcenter",
        "org.kde.krita",
        "com.obsproject.Studio",
        "blender",
        "org.openrgb.OpenRGB"
    ]

    [shell.panel]
    control_center_placement = "floating"
    control_center_position = "center"
    session_placement = "floating"
    session_position = "center"

    [shell.screen_corners]
    enabled = true
    size = 16

    [shell.screenshot]
    directory = "/home/niximkopf/Pictures/screenshots"

    [shell.session]
    show_shortcuts = false

[system.monitor]
enabled = false

[theme]
builtin = "Catppuccin"
community_palette = "Lilac AMOLED"
mode = "dark"
pure_black_dark = true
source = "community"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "qt" ]
    community_ids = [ "opencode", "discord", "blender", "steam", "kitty", "yazi" ]

[wallpaper]
directory = "/home/niximkopf/.nixos/assets/wallpaper"
directory_dark = "/home/niximkopf/Pictures/wallpaper"

    [wallpaper.default]
    path = "/home/niximkopf/.nixos/assets/wallpaper/holy_nixos.png"

    [wallpaper.last]
    path = "/home/niximkopf/Pictures/wallpaper/wallhaven-5ypy88-logo.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/niximkopf/.nixos/assets/wallpaper/holy_nixos.png"

    [wallpaper.monitors.DP-1]
    path = "/home/niximkopf/Pictures/wallpaper/wallhaven-5ypy88-logo.png"

    [wallpaper.monitors.DP-2]
    path = "/home/niximkopf/.nixos/assets/wallpaper/wallhaven-p9yy39.png"

    [[wallpaper.favorite]]
    community_palette = "Lilac AMOLED"
    palette_source = "community"
    path = "/home/niximkopf/.nixos/assets/wallpaper/wallhaven-5ypy88-violett.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Lilac AMOLED"
    palette_source = "community"
    path = "/home/niximkopf/.nixos/assets/wallpaper/wallhaven-p9yy39.png"
    theme_mode = "dark"

[weather]
enabled = false

[widget.audio_visualizer]
capsule = true
capsule_border = "on_primary"
capsule_fill = "primary"
capsule_opacity = 0.65000000000000002
capsule_padding = 0
capsule_radius = 6
color_1 = "on_primary"
color_2 = "on_primary"
show_when_idle = true
width = 128

[widget.battery]
show_label = false

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.cat]
audio_spectrum = true
capsule = true
capsule_border = "primary"
capsule_opacity = 0.75
capsule_radius = 6
scale = 1.1000000000000001
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clipboard]
enabled = false

[widget.clock]
anchor = true
capsule = true
capsule_border = "primary"
capsule_opacity = 0.75
capsule_radius = 6
format = "{:%H:%M}\\n--\\n{:%d\\n%m}"

[widget.control-center]
enabled = false

[widget.launcher]
capsule = true
capsule_border = "primary"
capsule_opacity = 0.75
capsule_radius = 6
custom_image = "/home/niximkopf/.nixos/assets/icons/nixos-customized (1).svg"

[widget.media]
enabled = false

[widget.network]
show_label = false

[widget.notifications]
enabled = false

[widget.recorder]
capsule = true
capsule_opacity = 0.55000000000000004
capsule_radius = 8
enabled = false
type = "noctalia/screen_recorder:recorder"

[widget.screenshot]
enabled = false

[widget.session]
capsule = true
capsule_border = "primary"
capsule_opacity = 0.75
capsule_radius = 6
icon_color = "error"

[widget.todo]
label = ""
show_label = false
type = "nightwatch75/todo:todo"

[widget.tray]
capsule = true
capsule_border = "primary"
capsule_opacity = 0.75
capsule_radius = 6
icon_color = "primary"

[widget.volume]
show_label = false

[widget.wallpaper]
enabled = false

[widget.widget_2]
type = "thepunkoff/pomodoro:widget"
widget-glyph-main = "time-duration-30"

[widget.workspaces]
capsule = true
capsule_border = "primary"
capsule_opacity = 0.75
capsule_padding = 8
capsule_radius = 6
scale = 1.1000000000000001
style = "minimal"
